package com.hss01248.media.mymediastore.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hss01248.media.mymediastore.bean.BaseMediaInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASE_MEDIA_INFO".
*/
public class BaseMediaInfoDao extends AbstractDao<BaseMediaInfo, String> {

    public static final String TABLENAME = "BASE_MEDIA_INFO";

    /**
     * Properties of entity BaseMediaInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FolderPathOrUri = new Property(0, String.class, "folderPathOrUri", false, "FOLDER_PATH_OR_URI");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property PathOrUri = new Property(2, String.class, "pathOrUri", true, "PATH_OR_URI");
        public final static Property FileSize = new Property(3, long.class, "fileSize", false, "FILE_SIZE");
        public final static Property UpdatedTime = new Property(4, long.class, "updatedTime", false, "UPDATED_TIME");
        public final static Property Type = new Property(5, int.class, "type", false, "TYPE");
    }


    public BaseMediaInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BaseMediaInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASE_MEDIA_INFO\" (" + //
                "\"FOLDER_PATH_OR_URI\" TEXT," + // 0: folderPathOrUri
                "\"NAME\" TEXT," + // 1: name
                "\"PATH_OR_URI\" TEXT PRIMARY KEY NOT NULL ," + // 2: pathOrUri
                "\"FILE_SIZE\" INTEGER NOT NULL ," + // 3: fileSize
                "\"UPDATED_TIME\" INTEGER NOT NULL ," + // 4: updatedTime
                "\"TYPE\" INTEGER NOT NULL );"); // 5: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASE_MEDIA_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BaseMediaInfo entity) {
        stmt.clearBindings();
 
        String folderPathOrUri = entity.getFolderPathOrUri();
        if (folderPathOrUri != null) {
            stmt.bindString(1, folderPathOrUri);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String pathOrUri = entity.getPathOrUri();
        if (pathOrUri != null) {
            stmt.bindString(3, pathOrUri);
        }
        stmt.bindLong(4, entity.getFileSize());
        stmt.bindLong(5, entity.getUpdatedTime());
        stmt.bindLong(6, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BaseMediaInfo entity) {
        stmt.clearBindings();
 
        String folderPathOrUri = entity.getFolderPathOrUri();
        if (folderPathOrUri != null) {
            stmt.bindString(1, folderPathOrUri);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String pathOrUri = entity.getPathOrUri();
        if (pathOrUri != null) {
            stmt.bindString(3, pathOrUri);
        }
        stmt.bindLong(4, entity.getFileSize());
        stmt.bindLong(5, entity.getUpdatedTime());
        stmt.bindLong(6, entity.getType());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2);
    }    

    @Override
    public BaseMediaInfo readEntity(Cursor cursor, int offset) {
        BaseMediaInfo entity = new BaseMediaInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // folderPathOrUri
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pathOrUri
            cursor.getLong(offset + 3), // fileSize
            cursor.getLong(offset + 4), // updatedTime
            cursor.getInt(offset + 5) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BaseMediaInfo entity, int offset) {
        entity.setFolderPathOrUri(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPathOrUri(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFileSize(cursor.getLong(offset + 3));
        entity.setUpdatedTime(cursor.getLong(offset + 4));
        entity.setType(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BaseMediaInfo entity, long rowId) {
        return entity.getPathOrUri();
    }
    
    @Override
    public String getKey(BaseMediaInfo entity) {
        if(entity != null) {
            return entity.getPathOrUri();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BaseMediaInfo entity) {
        return entity.getPathOrUri() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
