package com.hss01248.media.mymediastore.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hss01248.media.mymediastore.bean.BaseMediaFolderInfo;
import com.hss01248.media.mymediastore.bean.BaseMediaInfo;

import com.hss01248.media.mymediastore.db.BaseMediaFolderInfoDao;
import com.hss01248.media.mymediastore.db.BaseMediaInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseMediaFolderInfoDaoConfig;
    private final DaoConfig baseMediaInfoDaoConfig;

    private final BaseMediaFolderInfoDao baseMediaFolderInfoDao;
    private final BaseMediaInfoDao baseMediaInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseMediaFolderInfoDaoConfig = daoConfigMap.get(BaseMediaFolderInfoDao.class).clone();
        baseMediaFolderInfoDaoConfig.initIdentityScope(type);

        baseMediaInfoDaoConfig = daoConfigMap.get(BaseMediaInfoDao.class).clone();
        baseMediaInfoDaoConfig.initIdentityScope(type);

        baseMediaFolderInfoDao = new BaseMediaFolderInfoDao(baseMediaFolderInfoDaoConfig, this);
        baseMediaInfoDao = new BaseMediaInfoDao(baseMediaInfoDaoConfig, this);

        registerDao(BaseMediaFolderInfo.class, baseMediaFolderInfoDao);
        registerDao(BaseMediaInfo.class, baseMediaInfoDao);
    }
    
    public void clear() {
        baseMediaFolderInfoDaoConfig.clearIdentityScope();
        baseMediaInfoDaoConfig.clearIdentityScope();
    }

    public BaseMediaFolderInfoDao getBaseMediaFolderInfoDao() {
        return baseMediaFolderInfoDao;
    }

    public BaseMediaInfoDao getBaseMediaInfoDao() {
        return baseMediaInfoDao;
    }

}
